name: test_case_mobile_developer
description: 'Test Case Mobile Developer.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^2.4.4
  dartz: ^0.10.1
  dio: ^5.8.0+1
  get_it: ^8.0.3
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.6
  animations: ^2.0.11
  logger: ^2.5.0
  flutter_secure_storage: ^9.2.4
  equatable: ^2.0.7
  flutter_osm_plugin: ^0.70.4
  geocoding: ^3.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.11
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  json_serializable: 6.8.0

flutter:
  uses-material-design: true

  assets:
    - .env
